### ISSUE TITLE
Command line flags for executing Edge should be part of the docs

### ISSUE THREAD

**Issue by codepo8** [MicrosoftDocs/edge-developer#2249] opened 2022-10-13 18:05 UTC
**Description of the issue**: For years now the canonical place to go to in order to learn about available command line flags for executing chromium is Peter Beverloo's blog. It would be great to have [this information](https://peter.sh/experiments/chromium-command-line-switches/) als in the official Edge docs.

**Comment by captainbrosset** [comment] 2022-10-14 07:30
This is a duplicate of #1354 which is now closed.
CC @Reezaali

**Comment by captainbrosset** [comment] 2022-11-07 18:29
I'll close this issue now. This is more of an Edge issue than a documentation issue since we'd need to auto-generate the flags from the code first. I'll make sure this is tracked at the Edge level, and close this issue.

**Closed by captainbrosset** 2022-11-07 18:29 UTC
Labels: needs-more-info, cat: general
