### ISSUE TITLE
Docs seem out of date with new release

### ISSUE THREAD

**Issue by stratospheres** [MicrosoftDocs/edge-developer#819] opened 2020-07-16 20:23 UTC
Hey, if I install an older pre-release version (e.g. 0.9.538-prerelease), I can find the webview2 control at the location/assembly specified in the article. However, if I use the newer "stable" version (0.9.538), I get build failures saying that the 

```
The name "WebView2" does not exist in the namespace "clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf".
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Microsoft Edge WebView 2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by LanceMcCarthy** [comment] 2020-07-21 22:35
I can confirm this as well.

**Comment by pagoe-msft** [comment] 2020-07-21 23:36
@stratospheres and @LanceMcCarthy 

Are you using the pre-release package?

**Comment by LanceMcCarthy** [comment] 2020-07-21 23:49
No, the prerelease one actually works per the instructions. It is the latest release that doesn't (the prereleases's updated rollout).

The official demo project is also using the older prerelease version as well, so I couldn't find any  further resources on how to instantiate WebView2 (after prerelease)

**Comment by pagoe-msft** [comment] 2020-07-22 15:22
@LanceMcCarthy 

Are you getting this error with package 0.9.579-prerelease?

**Comment by Reezaali** [comment] 2020-07-30 21:55
I'll go ahead and close this issue because an answer was provided in the linked issue. Thank you.

**Closed by Reezaali** 2020-07-30 21:55 UTC
