### ISSUE TITLE
Using  Edge Chromium with Selenium Grid. (Using Selenium Tools for Microsoft Edge) msedge.selenium_tools in Python

### ISSUE THREAD

**Issue by jaimini76** [MicrosoftDocs/edge-developer#670] opened 2020-05-14 01:30 UTC
Can someone please provide an example on how can we use Edge Chromium with Selenium Grid  in python?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=python)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment] 2020-08-14 23:38
Similar to https://github.com/MicrosoftDocs/edge-developer/issues/612

**Comment by captainbrosset** [comment] 2021-11-22 14:26
Closing as a duplicate of #612.

**Closed by captainbrosset** 2021-11-22 14:26 UTC
Labels: cat: webdriver
