### ISSUE TITLE
Access external webpages

### ISSUE THREAD

**Issue by orlandobianco** [MicrosoftDocs/edge-developer#2633] opened 2023-06-09 14:31 UTC
im unable to view webpages that are not on my local machine, is it possible to use this extension to access external webpages? in my case i've to access a webpage on hosted on a webserver inside a vpn

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94630cc3-dd1a-7c4d-1784-c1d8bd7f16b4
* Version Independent ID: 94630cc3-dd1a-7c4d-1784-c1d8bd7f16b4
* Content: [Getting in touch with the Microsoft Edge DevTools Extension team - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/contact-devtools-extension-team)
* Content Source: [microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/contact-devtools-extension-team.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/contact-devtools-extension-team.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment] 2023-06-09 17:23
Yes, external sites are supported, like in Edge.  
1. In VS Code, in Activity Bar on left, click **Microsoft Edge Tools** icon.
2. Click the **Launch Instance** button.  The **Edge DevTools** tab and the **Edge DevTools Browser** tab open in VS Code.
3. In VS Code, in the **Edge DevTools Browser** tab, in the Address bar, replace the default URL by microsoft.com, and then press **Enter**.  The external site appears, and the Address bar shows: https://www.microsoft.com/en-us/

![image](https://github.com/MicrosoftDocs/edge-developer/assets/45407486/25b399c0-1dda-4c54-806f-81dbbbfb1f87)

**Comment by captainbrosset** [comment] 2023-06-13 08:21
Thanks for reaching out @orlandobianco, and thanks @mikehoffms for providing an answer.
I'm going to close this for now, since the question was answered. But please do comment here again if the problem isn't resolved.

Also, for bugs and feature requests to the extension itself (rather than feedback about the docs), then please open issues on this repository instead: https://github.com/microsoft/vscode-edge-devtools/

**Closed by captainbrosset** 2023-06-13 08:21 UTC
Labels: triage-needed
