### ISSUE TITLE
configuring the edge webdriver with selenium

### ISSUE THREAD

**Issue by krb-vci** [MicrosoftDocs/edge-developer#1724] opened 2022-02-07 20:08 UTC
The webdriver documentation pages directed me here to address my issue.

I am using the latest msedgedriver and selenium (3.14 - I did not upgrade because I also need to test opera, which is not supported in selenium 4).

I need to enable popup blocking, and cannot find the correct string to use.  I believe I need to add something like:
                        options.AddAdditionalCapability("disable-popup-blocking", true);

But that does not work, and i cannot find documentation for the popup blocking setting in webdriver options

Please help.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6f6ed7-a789-502b-4c84-e823fa8e58ce
* Version Independent ID: dee3faf2-ef14-c323-6307-ebe204670f59
* Content: [Overview of DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/#opening-devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by bwalderman** [comment] 2022-02-07 23:31
Hi @krb-vci. Since you are using Selenium 3, you will need to use https://github.com/microsoft/edge-selenium-tools if you are not doing so already. The EdgeOptions class provided with Selenium 3 was intended for legacy Edge (EdgeHTML) and does not work with current versions of Edge (Chromium).

`options.AddAdditionalCapability` is only for adding one of the EdgeDriver capabilities listed at https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options#edgeoptions-object and is only needed if Selenium is missing an appropriate property or method to use instead.

`"disable-popup-blocking"` is an Edge/Chrome command line argument, not a capability, and both ChromeDriver and EdgeDriver include it by default. To enable popup blocking, you will need to tell EdgeDriver to exclude this argument. This line should do it:

`options.AddExcludedArgument("disable-popup-blocking")`

Hope this helps!

**Comment by krb-vci** [comment] 2022-02-08 00:02
Hi Brandon,
I am using selenium 3.14 with the latest version (at least according to the update feature of edge on my machine - it is edge 98.0.1108.43.  The msedgedriver version I am using is the x64 version for edge version 98.
The line you showed above (options.AddExcludedArgument("disable-popup-blocking")) is exactly what i am using for Chrome and Opera, but with edge i get an error stating that AddExcludedArgument is not available in EdhgeOptions.
My instantiation code is as follows:

`  var service = OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService(driverDir, @"msedgedriver.exe");
   service.UseVerboseLogging = true;
   service.Start();
   var options = new OpenQA.Selenium.Edge.EdgeOptions();
   // options.AddExcludedArgument("disable-popup-blocking");  // will not compile
   // options.AddAdditionalCapability("disable-popup-blocking", true); // will compile, but does not turn off blocker
   driver = new RemoteWebDriver(service.ServiceUrl, options);`

I am stuck, and appreciate any info...

**Comment by bwalderman** [comment] 2022-02-08 02:04
The built-in classes from Selenium 3, like `OpenQA.Selenium.Edge.EdgeDriverService` and `OpenQA.Selenium.Edge.EdgeOptions`, do not support the latest Chromium-based versions of Edge and are missing Chromium-specific methods like `AddExcludedArgument`. To use Selenium 3 with the latest versions of Edge and msedgedriver, you will need to use https://github.com/microsoft/edge-selenium-tools which is our compatibility solution for users who are not able to upgrade to Selenium 4.

Follow the instructions at that link to install the library. Then, update your code to use the `Microsoft.Edge.SeleniumTools.EdgeDriverService` and `Microsoft.Edge.SeleniumTools.EdgeOptions` classes from that library instead. You will also need to set `EdgeOptions.UseChromium` to `true`. I've updated your sample code below:

```csharp
var service = Microsoft.Edge.SeleniumTools.EdgeDriverService.CreateChromiumService(driverDir);
service.UseVerboseLogging = true;
service.Start();

var options = new Microsoft.Edge.SeleniumTools.EdgeOptions();
options.UseChromium = true;
options.AddExcludedArgument("disable-popup-blocking");

driver = new RemoteWebDriver(service.ServiceUrl, options);
```

**Comment by krb-vci** [comment] 2022-02-08 02:13
Thanks.  I won’t be able to do until tomorrow.  Will respond again after I try.

**Comment by krb-vci** [comment] 2022-02-08 18:59
Brandon,
Thanks so much – that worked!
Now I just need to convince the Selenium 4 team to support Opera…

**Comment by captainbrosset** [comment] 2022-02-09 12:53
Thank you both for figuring this out! Going to close the issue now.

**Closed by captainbrosset** 2022-02-09 12:53 UTC
Labels: needs-more-info, cat: webdriver
