### ISSUE TITLE
Not Compatible with .net core 3.1

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/edge-developer#477] opened 2020-02-16 21:19 UTC
We get error if we use unstable `Selenium 4.00-alpha04`  
```text
Could not load file or assembly 'netstandard2.0assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 
```
Update the document accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#feedback)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by thedustmonkey** [comment] 2020-02-18 20:32
.NET Core 3.1 compatibility issues w/ Se 4.0-a04 confirmed — this issue effectively shuts down integration into and further exploration of Chromium Edge in existing automation platform until resolved.

**Comment by bwalderman** [comment] 2020-02-20 17:17
This is a known issue with Selenium Alpha 04 and has recently been fixed in their repo:
[https://github.com/SeleniumHQ/selenium/issues/7932](https://github.com/SeleniumHQ/selenium/issues/7932)

However, Selenium has not yet published a release that includes the fix. The fix should be included in Alpha 05 once that becomes available.

**Comment by zoherghadyali** [comment] 2020-04-20 17:18
@pmahend1 and @thedustmonkey, have you tried using the latest [Selenium4.0.0-alpha05](https://www.nuget.org/packages/Selenium.WebDriver/4.0.0-alpha05)? It should contain the fix you need so definitely let us know how that goes for you!

**Comment by Reezaali** [comment] 2020-04-20 20:16
Thanks for reporting this issue. Since the document has been updated, I'll go ahead and close this issue. Thanks again!

**Closed by Reezaali** 2020-04-20 20:16 UTC
Labels: cat: devtools, doc-bug
