### ISSUE TITLE
Update tutorial to use Manifest V3

### ISSUE THREAD

**Issue by eclipse439** [MicrosoftDocs/edge-developer#2012] opened 2022-06-15 22:13 UTC
[Manifest V3](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format) has now been out for some time, so the tutorial should be updated to use the new format. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial, part 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment] 2022-06-16 08:30
Yes, very good point. Thank you for filing this!

**Comment by captainbrosset** [comment] 2022-06-16 08:31
Because issue #1878 already tracks this, let's close this one as a duplicate.

Duplicate of #1878.

**Closed by captainbrosset** 2022-06-16 08:31 UTC
Labels: cat: extensions
