### ISSUE TITLE
WebView2 tutorial missing information

### ISSUE THREAD

**Issue by carlossanlop** [MicrosoftDocs/edge-developer#890] opened 2020-09-06 19:18 UTC
The WebView2 tutorial is missing information that will ensure the object will be properly loaded. I described the details of the missing information in the following comment issue:
https://github.com/MicrosoftEdge/WebViewFeedback/issues/228#issuecomment-687873636

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#feedback)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by RussKie** [comment] 2020-09-08 02:20
It would be good to fix the sizing of images (they all over the place) and code snippets as well. 

E.g. the code example in step 4 provides several bad suggestions.
1. If the form was designed in the desirer, why does user need to wire up a handler manually?
1. There is no need to wire up event handlers when an implementation can be plumbed via an override - in the latter case there is no allocations for handlers.

```cs
public Form1()
{
    InitializeComponent();
    this.Resize += new System.EventHandler(this.Form_Resize);
}

private void Form_Resize(object sender, EventArgs e)
{
    webView.Size = this.ClientSize - new System.Drawing.Size(webView.Location);
    goButton.Left = this.ClientSize.Width - goButton.Width;
    addressBar.Width = goButton.Left - addressBar.Left;
}
```

should look like this:
```cs
public Form1()
{
    InitializeComponent();
}

protected override void OnResize(EventArgs e)
{
    base.OnResize(e);

    webView.Size = this.ClientSize - new System.Drawing.Size(webView.Location);
    goButton.Left = this.ClientSize.Width - goButton.Width;
    addressBar.Width = goButton.Left - addressBar.Left;
}
```

But the biggest issue with the overall example IMO is that we require a user to perform manual layouts. I suggest to update the layout of the form in a way that handles resize and layout events automatically.
Windows Forms provides [`Control.Dock`](https://docs.microsoft.com/dotnet/api/system.windows.forms.control.dock) and [`Control.Anchor`](https://docs.microsoft.com/dotnet/api/system.windows.forms.control.anchor) properties that take care of control placement, as well as [`TableLayoutPanel`](https://docs.microsoft.com/dotnet/api/system.windows.forms.tablelayoutpanel) and [`FlowLayoutPanel`](https://docs.microsoft.com/dotnet/api/system.windows.forms.flowlayoutpanel) controls that facilitate complex layouts.

I think it is important to make our examples as good as they can be, as users often copy code and then build on top of it and deploy into production.

**Comment by Reezaali** [comment] 2021-02-27 01:50
Closing this issue because I opened an issue on the engineering team's feedback repo. Thanks.

**Closed by Reezaali** 2021-02-27 01:50 UTC
Labels: ADO, cat: webview
