### ISSUE TITLE
3D View (DOM to 3D) in DevTools doesn't work anymore :(

### ISSUE THREAD

**Issue by robozb** [MicrosoftDocs/edge-developer#2865] opened 2023-10-11 00:59 UTC
Error message: 

"Some Microsoft DevTools components are missing. 3D View will be unavailable until they are installed. You must be connected to the internet..."

I'm connected to the net. Reinstal didn't help. 

![image](https://github.com/MicrosoftDocs/edge-developer/assets/8656998/3d6c2612-bb9b-4723-86bf-0dbb9f59d75d)

**Comment by captainbrosset** [comment] 2023-10-11 07:31
Thanks for reporting this, and sorry about the regression. We are working as quickly as we can to address this bug.
I'll close this particular issue because the bug is actually already tracked here: https://github.com/MicrosoftEdge/DevTools/issues/186
Feel free to follow that issue to stay updated with it.

**Closed by captainbrosset** 2023-10-11 07:31 UTC
Labels: triage-needed
