### ISSUE TITLE
Geolocation override doesn't work -- Edge ignores the setting

### ISSUE THREAD

**Issue by Scribliotech** [MicrosoftDocs/edge-developer#917] opened 2020-09-22 20:32 UTC
These instructions don't work consistently. Perhaps it's a bug in the Chromium engine, because I see the same options in Google's Chrome and it has the same problem. These instructions seem to usually work the first time for a new profile, then usually don't work again after that. Instead, the browser reverts to showing the actual location of the browser and completely ignores the override. 

If this is user error and not a bug in the browser, then the instructions on this page are wrong, because following them to the letter yields the problems described above. Either way, these instructions don't match with the browser behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adbf0ab-a03d-f7ed-76a4-20ad3127ade9
* Version Independent ID: 79112442-6921-c286-8f39-c079fc2d526b
* Content: [Override geolocation with Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/geolocation)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment] 2021-07-12 10:19
This issue seems like a duplicate of #901 and should probably be closed.

**Closed** 2021-07-13 10:51 UTC
Labels: cat: devtools
