### ISSUE TITLE
no "Rendering" tab in devtools and two search results for dark theme emulation mentioned in the docs page

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/edge-developer#1648] opened 2021-12-22 00:32 UTC
[Enter feedback here]

I saw this auto dark mode emulation for chrome somewhere else and I have found your page about that "Emulate dark or light schemes" in Edge.

But the problem is there simply is no "Rendering" tab in devtools.

trying with ctrl+shift+P, and searching for "dark" I can see there is a Rendering tab implemented but is just not showing in the tabs.

and more, there are 2 "emulate auto dark mode" results and I have to click on that command twice to activate and see the theme on the page.

Microsoft Edge on Windows 10 21h2 fully updated to date.
Version 96.0.1054.62 (Official build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc385dd2-fb44-9553-7350-9813d104b3dc
* Version Independent ID: a3db4e1e-87ce-d35c-435a-8ff4a59d4dd3
* Content: [Emulate dark or light schemes in the rendered page - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation)
* Content Source: [microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment] 2021-12-22 00:56
The article might need clarification.  Maybe the Rendering tool's tab is hidden due to narrow window, and you need to click >> to select & show the Rendering tab.

Here are my findings with Microsoft Edge 96:

Right now, I'm in a state where the Rendering tab gets added to the main (upper) toolbar instead of the Drawer (lower toolbar): 1. On the main toolbar, if the Rendering tab is open, click x to close the **Rendering** tab. 
2. Press Ctrl+Shift+P to open the Command Menu.
3. Type "render": the "Show Rendering [Drawer]" command appears.  
4. Select the **Show Rendering [Drawer]** command.
Actual result: the Rendering tab appears on the main toolbar (as the rightmost tab).  
Expected result: The Rendering tab should appear (I think) on the Drawer toolbar.  Next, 
1. On the main toolbar, on the Rendering tab, click x to close it.  
2. On the Drawer toolbar, click the More Tools (+) button, and then select Rendering.
Result: The Rendering tab appears on the Drawer toolbar, as expected.

**Comment by yilmazdurmaz** [comment] 2021-12-22 01:30
@mikehoffms  thanks for the nice additions.

for the first part of the issue, it seems I have just misread "+" (more tools)  to be ">>" (more tabs). it is an easy-to-make mistake because both are next to each other. I have used ">>" all the time but "+" only a couple of times so far over many years. I was in the mood Edge team haven't yet integrated such features :)

but that also makes another story, because it seems an item will show up only in one of them. if I close it with its "x" button, it goes back to "more tools", if I select another tool it just goes back to "more tabs".

I think it would be better to make this 1st item in the "using the Rendering tool" to-do list also mention ">>" (more tabs).

**Comment by mikehoffms** [comment] 2021-12-22 01:52
Notes; I'll edit this posting.  Regarding this previous message:

Paragraph 1:
"I have just misread..."  I want to clarify the article to prevent misreading; thanks for the suggested rewording in your paragraph 3 above.

Paragraph 2:
"an item will show up only in one of them [_ie More tabs or More Tools_]. if I close it with its "x" button, it goes back to "more tools", if I select another tool it just goes back to "more tabs"."
Confirmed: Rendering appears in either **More tabs** (>>) if Rendering tool is open and window is narrow, or, appears in **More Tools** (+) if the Rendering tool isn't currently open.

Paragraph 3:
"make this 1st item in the "using the Rendering tool" to-do list also mention ">>" (more tabs)."
That is, in the section:
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation#emulating-dark-or-light-mode-using-the-rendering-tool
change:
In DevTools, open the Rendering tool. To do this, you might need to select the More Tools (+) icon on the main toolbar and then select Rendering.
to:
In DevTools, open the Rendering tool. To do this, you might need to select the **More Tools** (+) icon on the main toolbar and then select Rendering.  Or, if the Rendering tool is already open but hidden, select the **More tabs** (>>) icon on the main toolbar.

**Actions to take:**
* I'm entering a work item for the above article edit...
Other possible action items above:
* Enter a work item (bug) if not entered already, that the _Emulate auto dark mode [Rendering]_ command appears twice in the Command Menu.
* Depending on the above bug fix, maybe enter a bug about having to click that command twice.  However, that might be No Repro, especially if there were only a single command.  Requires more testing of each instance of the command to see if the command does nothing when it should toggle dark vs light mode.

**Comment by mikehoffms** [comment] 2021-12-22 02:04
@captainbrosset - attention re: "Other possible action items above", above.

**Comment by captainbrosset** [comment] 2022-01-03 09:10
Thanks @mikehoffms. I will create a bug for the DevTools team to investigate the command that appears twice, and having to click it twice for it to work.
The last one (+ button wrapping on the next line) is already known by the team.

**Closed** 2022-01-18 19:33 UTC
Labels: ADO

**Comment by captainbrosset** [comment] 2022-01-20 09:16
For information, the bug whereby the command appears twice is fixed in Edge 98 now (beta at the moment of writing, but will become stable early February).
