### ISSUE TITLE
Typos in the Microsoft Edge Add-ons API documentation

### ISSUE THREAD

**Issue by abhishek-shanthkumar** [MicrosoftDocs/edge-developer#1388] opened 2021-08-12 06:56 UTC
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#terminology
  - product ID
    - With the dashes, the GUID string is 36 characters long. Skip the "32-character" part, or say "128-bit GUID".
    - This may be better? "... associated with a product **on** Partner Center"
  - submission
    - This may be better? "... being submitted to an existing product **on** Partner Center"
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#using-the-api-endpoints
  - Under all the APIs, the part `Header Parameters: $TOKEN: the access token` should be `Header Parameters: Authorization: Bearer $TOKEN` because the header name is `Authorization`.
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#using-the-api-endpoints
  - Make these two statements uniform in tone and words: "For the first version of a product, the status field has the following values" and "For subsequent submissions, you'll receive either of the following values"
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#status-codes
  - For the Status code 200, the description should say "OK" and not "ok".
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#request-headers
  - Under all the request headers, it should be `Authorization: Bearer <auth token>` and not just `Authorization: <auth token>`.
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#uri-parameters-1
  - The subtext "You can specify the following additional parameters on the request URI:" is unnecessary and confusing (applicable to all the URI parameters sections on the page).
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response-headers
  - The Location URL contains extra backslashes.
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response-headers
  - The Product ID URL parameter is missing.
- https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response-headers-2
  - The subtext "When there is a valid publish request, the response returns a header:" is unnecessary.
  - The Location URL contains quotation marks.

**Comment by ashishnirvana1** [comment] 2021-08-23 17:54
> https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#using-the-api-endpoints
Make these two statements uniform in tone and words: "For the first version of a product, the status field has the following values" and "For subsequent submissions, you'll receive either of the following values"

@abhishek-shanthkumar  Where is this? Can you clarify?

**Comment by mikehoffms** [comment] 2021-12-11 03:09
@ashishnirvana1 

I assessed the status of the reported items, to move toward closing this Issue.  All reported items were fixed except the one point Ashish asked about.  The answer is:

The issue is not found in using-addons-api.md; it's in addons-api-reference.md, at 
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response 
The requested change (not done), is:

Make these two statements uniform in tone and words:
* "For the first version of a product, the status field has the following values"
* "For subsequent submissions, you'll receive either of the following values"

**Comment by captainbrosset** [comment] 2021-12-13 14:21
Thanks for tracking this Mike. Let's close this issue when the work item you mentioned is fixed.

**Comment by mikehoffms** [comment] 2022-05-27 19:06
The section that actually contained the wording about "first / subsequent" no longer has any such wording:
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response
Closing this Issue as Completed.

**Closed by mikehoffms** 2022-05-27 19:06 UTC
Labels: cat: extensions, ADO
