### ISSUE TITLE
Enabling developer console for Edge on iPad (iOS 13)

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/edge-developer#559] opened 2020-03-31 13:23 UTC
I am using Edge on an iPad 6th gen (iOS 13). Could you please document how Developer console can be enabled in this context?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462f093f-9486-8086-da81-c689b7ef7d9e
* Version Independent ID: 0424a5af-15a6-1ccd-5732-12edb757838a
* Content: [DevTools - Console - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console#feedback)
* Content Source: [microsoft-edge/devtools-guide/console.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ststimac** [comment] 2020-04-06 22:51
We don't have a way to do this currently but there are a few workarounds that I'm looking into getting.

**Comment by ststimac** [comment] 2020-04-07 22:43
Hi @kmathewmk! 

**Currently, we do not support iOS remote debugging.** This is ultimately due to some nuances with how our Microsoft Edge mobile apps are built. On iOS, as I understand it, the Microsoft Edge app uses [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) which basically means that the underlying web platform that is rendering HTML/CSS/JavaScript is WebKit.

I have a couple next steps that could help:

- If the issue reproduces on Safari, which is also using WebKit as the underlying web platform, you should be able to follow the instructions here: [https://support.brightcove.com/debugging-mobile-devices](https://support.brightcove.com/debugging-mobile-devices) to remotely debug Safari/Microsoft Edge on iOS with Safari’s Web Inspector tools on macOS.
- If the issue is specific to Edge on iOS, another option is to ask the MMX team that builds that app to produce a version which enables debugging WKWebView.
- Finally, this hasn’t been verified/tested recently and I wouldn’t be surprised if it doesn’t work but this GitHub repo: [https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) is supposed to provide an adapter between things like the Edge DevTools, VS Code, etc. and WebKit on iOS. If you do use this, please let me know how that goes for you.

**Comment by kmathewmk** [comment] 2020-04-09 18:40
Thanks a lot for your detailed response.

>remotely debug Safari/Microsoft Edge on iOS with Safari’s Web Inspector tools on macOS.
I am aware of this option but it requires a macOS device

> another option is to ask the MMX team that builds that app to produce a 
> version which enables debugging WKWebView
Would https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider be a good way to reach the team?

**Comment by ststimac** [comment] 2020-04-16 17:42
@kmathewmk yes that would be the best place to start a conversation for this.

**Comment by zoherghadyali** [comment] 2020-06-11 00:17
We've also updated the documentation here: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/ with PR #745 so I'm closing this issue. Thank you for using Microsoft Edge and sharing your feedback with us!

**Closed by zoherghadyali** 2020-06-11 00:17 UTC
Labels: cat: devtools, product-question
