### ISSUE TITLE
Implement chrome.gcm API

### ISSUE THREAD

**Issue by joaomgcd** [MicrosoftDocs/edge-developer#449] opened 2020-01-28 09:18 UTC
Would it be possible for Edge to implement the chrome.gcm API so that extensions can receive push messages?

**Comment by CCninja86** [comment] 2020-02-11 21:28
Definitely this. It's a deal breaker for a lot of people, including myself.

**Comment by notenoughtech** [comment] 2020-02-12 21:06
I second that

**Comment by e2zippo** [comment] 2020-02-17 07:20
Any news on this? I see that Edge is on v80 now.

**Comment by Wolfbeta** [comment] 2020-03-04 01:13
I was absolutely in love with Edge Chromium until I came to realize it was the root cause of me not being able to copy and paste between my phone and laptop anymore.  @joaomgcd is a prolific developer, and Microsoft would be remiss to ignore this feature request. 

Until then I'll be returning to Chrome. You were so close, Microsoft. 20+ years of IE hell almost forgiven.

**Comment by sihde** [comment] 2020-03-04 23:21
@joaomgcd , according to Google the chrome.gcm is deprecated and the solution is to [migrate to FCM](https://developers.google.com/cloud-messaging/chrome/chrome-migrate-fcm). Is that an option? That page says the FCM SDK works on any browser that [supports Push API](https://caniuse.com/#feat=push-api) which includes Edge 79 and 80 (the Chromium-based versions).

**Comment by joaomgcd** [comment] 2020-03-06 13:50
I already migrated Join to FCM but Chrome still uses the chrome.gcm API to deliver the messages. They did not remove that part yet.
However the fcm SDK for javascript (last time I checked) doesn't support multiple registration tokens which Join needs to stay low cost as it is now...

**Comment by Joecascio2000** [comment] 2020-04-21 20:46
Sadly, I ended up here because of this exact issue. +1 for Microsoft correcting this.

**Comment by gebansal** [comment] 2020-06-09 10:46
We do not have any plans of providing chrome.gcm in Edge because it depends on Google's push messaging service. The use of GCM requires developers to register with developers.google.com, which creates a secret used for authentication.  This prevents us from standing up a Microsoft service that offers equivalent functionality since we cannot authenticate developers.

As an alternative, we request you to use service worker push messaging as a replacement for chrome.gcm in Edge. Service worker push messaging uses Microsoft’s push messaging service in Edge and Google’s push messaging service in Chrome.  Both push services implement the same IETF standards so the push messaging services should work the same. Here’s a good reference for the same: https://web-push-book.gauntface.com/introduction/.

**Comment by gebansal** [comment] 2020-06-17 06:52
We are closing this issue for now. If you think, there are some unanswered questions, please feel free to either reopen this issue or create a new one.

**Comment by Simpuhl** [comment] 2020-07-10 02:19
This should be re-opened. Many addons need this or at least a workaround

**Comment by gebansal** [comment] 2020-08-05 19:22
@Simpuhl as a workaround, we request you to use service worker push messaging as a replacement for chrome.gcm in Edge. 
Is there a specific issue that you are facing that we could help with?

**Comment by Simpuhl** [comment] 2020-08-05 19:25
> @Simpuhl as a workaround, we request you to use service worker push messaging as a replacement for chrome.gcm in Edge.
> Is there a specific issue that you are facing that we could help with?

I just started using Messages app and it works with Edge. So I am going to stop using the Join app

**Comment by PaddyFloch** [comment] 2020-08-05 19:52
Hi guys ! Glad to see this issue reopened, I am an avid Join user but not since it sort of shutdown when I switched to Edge. Now @joaomgcd is a great developer and as I understand it it requires chrome.gcm or something like that to keep the cost low.... I am not as experienced as he is. I would love to see this app work again, that makes me sad to see people dropping out of Join because of this compatibility issue. Thanks guys and much love Edge is a superb browser ! Hope we can resolve this soon enough. ;)

**Comment by darthShadow** [comment] 2020-08-05 19:57
Thanks to @joaomgcd, Join has been available for testing on Microsoft Edge for a few weeks now: https://www.reddit.com/r/JoinApp/comments/hbjagc/dev_join_on_firefox_and_edge_available_for/

**Comment by PaddyFloch** [comment] 2020-08-06 06:49
@darthShadow Thank you so much for your answer I didn't know about that and now I do and I'm hyped !  😄🤙

**Comment by ArestouMars** [comment] 2020-12-01 01:10
Please add this. The current work around is weird.

**Comment by gebansal** [comment] 2021-01-27 07:07
I request you to reach out to us at ext_dev_support@microsoft.com. We'll try our best to either offer an alternative or help resolve the current issue.

**Comment by gebansal** [comment] 2021-02-09 17:14
We are closing this issue for now. We are tracking only documentation related queries here. For any product related queries, do navigate to the Contact us (https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-us) page and reach out to the Edge extensions team directly. Thank you!

**Closed by gebansal** 2021-02-09 17:14 UTC
Labels: cat: extensions, needs-more-info, product-question, support-request
